export type AgeTier = '3-4' | '5-6' | '7-8' | '9-10' | '11-12+';

export interface QuestionItem {
  text: string;
  observation: string;
}

export const DIMENSIONS = [
  { key: 'Communication', label: 'Communication' },
  { key: 'Social', label: 'Social' },
  { key: 'Cognitive', label: 'Cognitive / Academic' },
  { key: 'Motor', label: 'Motor' },
  { key: 'Autonomy', label: 'Autonomy / Self-Care' },
  { key: 'Behavior', label: 'Behavior / Emotional Regulation' },
];

export const AGE_TIER_LABELS: Record<AgeTier, string> = {
  '3-4': 'Early Preschool (3–4 years)',
  '5-6': 'Late Preschool / Early Elementary (5–6 years)',
  '7-8': 'Elementary I (7–8 years)',
  '9-10': 'Elementary II (9–10 years)',
  '11-12+': 'Middle School / Adolescent (11–12+ years)',
};

export const LIKERT_LABELS: Record<number, string> = {
  1: 'Never / Not at all',
  2: 'Rarely / With heavy support',
  3: 'Sometimes / With moderate support',
  4: 'Often / With minimal support',
  5: 'Always / Independently',
};

export const QUESTIONS: Record<string, Record<AgeTier, QuestionItem[]>> = {
  Communication: {
    '3-4': [
      { text: 'Uses single words to request needs', observation: 'Describe the most common words used. How does the child communicate when they want food, toys, or attention? What happens when the word is not understood?' },
      { text: 'Follows 1-step instructions consistently', observation: 'Give examples of instructions followed (e.g., "give me the ball"). Does the child respond to their name? How often do they need gestures or pointing alongside verbal instruction?' },
      { text: 'Points to named objects in books or pictures', observation: 'Describe how the child responds when asked "Where is the cat?" Do they point, look, or become frustrated? Which types of objects are easiest/hardest?' },
      { text: 'Engages in joint attention (looking, showing)', observation: 'Describe a recent instance of the child showing or pointing to share interest. Do they check your face for reaction? How often does this happen per session?' },
      { text: 'Imitates sounds and gestures', observation: 'Which sounds or gestures are imitated most readily? Are there sounds the child avoids? Does imitation occur immediately or with delay?' },
      { text: 'Vocalizes displeasure or pleasure clearly', observation: 'Describe how the child expresses hunger, pain, joy, or refusal. Are vocalizations differentiated (different sounds for different needs)?' },
      { text: 'Recognizes familiar names when called', observation: 'Describe the child\'s response when their name is called in a busy room. Do they turn, look, or ignore? How many repetitions are typically needed?' },
      { text: 'Uses gestures or signs if verbal is limited', observation: 'Which gestures or signs does the child use? Are they self-invented or taught (e.g., baby signs)? How consistently are they used across settings?' },
      { text: 'Reacts to changes in tone of voice', observation: 'Describe how the child responds to a firm "no" versus a playful voice. Do they notice sarcasm or exaggerated intonation?' },
      { text: 'Babbles or vocalizes during play', observation: 'Describe the quality of babbling (consonant-vowel combinations, variety of sounds). Does vocalization increase or decrease in social vs. solitary play?' },
    ],
    '5-6': [
      { text: 'Uses 4–5 word sentences to express needs', observation: 'Provide examples of spontaneous sentences heard recently. Are sentences grammatically correct? Does the child omit words or use telegraphic speech?' },
      { text: 'Follows 2–3 step instructions without cues', observation: 'Give an example of a multi-step instruction the child completed. Were steps executed in order? Did they need visual checklist or repetition?' },
      { text: 'Answers WH-questions (who, what, where)', observation: 'Which WH-question type is easiest? Hardest? Describe a recent correct and incorrect response. Does the child answer with words, gestures, or silence?' },
      { text: 'Initiates conversations with peers or adults', observation: 'Describe a recent spontaneous initiation. What topics does the child initiate about? How often per session do they start an interaction?' },
      { text: 'Uses pronouns correctly (I, you, he, she)', observation: 'Does the child confuse "you" and "I"? Give examples of correct and incorrect pronoun use. Do they refer to themselves by name instead of "I"?' },
      { text: 'Asks questions to gain information', observation: 'What types of questions does the child ask (e.g., "What\'s that?", "Why?")? How many questions per session? Do they persist if the answer is insufficient?' },
      { text: 'Responds to greetings and farewells appropriately', observation: 'Describe the child\'s typical greeting behavior. Do they respond unprompted? Do they make eye contact? How do they say goodbye?' },
      { text: 'Uses AAC device or picture cards independently', observation: 'Which AAC system is used? Describe a recent instance of independent AAC use. How many buttons/symbols are actively used?' },
      { text: 'Understands emotion words (happy, sad, angry)', observation: 'Can the child label emotions in themselves and others? Give recent examples. Do they use emotion words spontaneously or only when prompted?' },
      { text: 'Narrates play activities aloud', observation: 'Describe the child\'s self-talk during play. Do they describe actions ("I\'m building"), assign roles, or create dialogue for toys?' },
    ],
    '7-8': [
      { text: 'Describes events in sequential order', observation: 'Ask the child "What did you do today?" and record their response. Did they use time words (first, then, last)? How many events were sequenced?' },
      { text: 'Follows complex multi-step classroom instructions', observation: 'Describe a recent classroom instruction the child followed independently. Which step types are hardest (spatial, temporal, conditional)?' },
      { text: 'Answers WHY and HOW questions logically', observation: 'Give examples of recent WHY/HOW responses. Were answers logical and causal? Did the child struggle with inference or stick to concrete facts?' },
      { text: 'Maintains topic for 3+ conversational turns', observation: 'Describe a recent conversation. How many turns were maintained? Who initiated topic shifts? Did the child introduce related topics or unrelated ones?' },
      { text: 'Uses past and future tense correctly in speech', observation: 'Record examples of past tense ("I went") and future tense ("I will go") use. Are irregular verbs correct? Is tense marking consistent?' },
      { text: 'Clarifies when not understood by others', observation: 'Describe what the child does when someone says "I don\'t understand." Do they repeat, rephrase, gesture, or become frustrated?' },
      { text: 'Understands non-literal language (sarcasm, jokes)', observation: 'Describe the child\'s reaction to sarcasm or jokes. Do they take statements literally? Can they explain why something is funny?' },
      { text: 'Combines AAC with verbal communication seamlessly', observation: 'Describe a recent instance where AAC and speech were used together. Does the child choose the most efficient modality for the context?' },
      { text: 'Describes emotional states of self and others', observation: 'How does the child describe their own feelings? Can they infer emotions from facial expressions, body language, and context? Give examples.' },
      { text: 'Describes cause-effect in stories or events', observation: 'When telling a story, does the child explain why things happened? Provide a recent example of cause-effect language used.' },
    ],
    '9-10': [
      { text: 'Summarizes a story with main idea and details', observation: 'Ask the child to summarize a recent story. Did they include the main idea, key characters, and sequence? What did they omit?' },
      { text: 'Understands figurative language (idioms, metaphors)', observation: 'Test with an idiom (e.g., "It\'s raining cats and dogs"). Did they understand figurative meaning? Which types of figurative language are easiest?' },
      { text: 'Participates in classroom discussions with peer turn-taking', observation: 'Describe participation in a recent group discussion. Did they raise their hand, build on peers\' ideas, or dominate/interrupt?' },
      { text: 'Repairs communication breakdowns independently', observation: 'Describe a recent misunderstanding. How did the child repair it? Did they ask for clarification, rephrase, or use gestures?' },
      { text: 'Uses complex sentence structures (if/then, because)', observation: 'Record examples of subordinate clauses used spontaneously. Are complex structures used in writing as well as speech?' },
      { text: 'Asks clarifying questions during instruction', observation: 'Does the child ask "What do you mean?" or "Can you repeat?" when confused? How often? Do they wait for appropriate pauses?' },
      { text: 'Understands persuasive intent in speech or text', observation: 'Can the child identify when someone is trying to convince them? Describe a recent example of their reaction to persuasion.' },
      { text: 'Chooses optimal communication mode for setting', observation: 'Does the child switch between whispering, speaking, writing, or AAC depending on noise level, audience, or topic? Give examples.' },
      { text: 'Interprets tone and body language in conversations', observation: 'Describe how the child reads social cues. Do they notice crossed arms, eye rolls, or enthusiastic tone? How do they adjust accordingly?' },
      { text: 'Summarizes and predicts in academic reading', observation: 'After reading a paragraph, can the child summarize it and predict what comes next? Describe accuracy and level of detail.' },
    ],
    '11-12+': [
      { text: 'Writes structured paragraphs with transitions', observation: 'Review a recent writing sample. Are topic sentences, supporting details, and transition words (however, furthermore) present and appropriate?' },
      { text: 'Interprets abstract or inferred meaning in text', observation: 'Describe the child\'s ability to read between the lines. Can they infer character motivation, theme, or author\'s purpose? Give examples.' },
      { text: 'Debates or argues a point with supporting evidence', observation: 'Describe a recent argument or debate. Did the child provide reasons and evidence? Could they acknowledge counterarguments?' },
      { text: 'Adjusts communication style based on audience or context', observation: 'Does the child speak differently to a teacher vs. a peer? Give examples of register shifts (formal vs. casual vocabulary and tone).' },
      { text: 'Uses nuanced vocabulary appropriate to subject matter', observation: 'Review academic vocabulary use across subjects. Does the child use domain-specific terms correctly (e.g., photosynthesis, democracy)?' },
      { text: 'Self-advocates verbally in unfamiliar settings', observation: 'Describe a time the child asked for help, accommodations, or clarification in a new environment. How did they phrase the request?' },
      { text: 'Critically evaluates spoken or written arguments', observation: 'Can the child identify weak evidence, bias, or logical fallacies? Describe a recent example of their critical analysis.' },
      { text: 'Troubleshoots AAC technology independently', observation: 'What does the child do when their AAC device malfunctions? Do they try fixes, switch modalities, or seek help immediately?' },
      { text: 'Navigates social nuance (sarcasm, white lies, politeness)', observation: 'Describe how the child handles indirect communication. Do they understand white lies to protect feelings? Can they use politeness markers appropriately?' },
      { text: 'Synthesizes information from multiple spoken or written sources', observation: 'Describe a recent project or assignment requiring synthesis. Could the child combine information from 2+ sources into a coherent whole?' },
    ],
  },
  Social: {
    '3-4': [
      { text: 'Plays alongside peers (parallel play)', observation: 'Describe the child\'s play near other children. Do they watch peers, copy actions, or remain oblivious? What toys or activities facilitate proximity?' },
      { text: 'Shows interest in other children', observation: 'How does the child show interest (looking, approaching, smiling)? Do they prefer certain children over others? What triggers disinterest?' },
      { text: 'Responds to social overtures (smiles, waves)', observation: 'Describe a recent peer greeting. Did the child respond reciprocally, ignore, or react negatively? How quickly did they respond?' },
      { text: 'Shows affection toward familiar people', observation: 'How does the child express affection (hugs, leaning in, giving objects)? Are they selective about who receives affection?' },
      { text: 'Recognizes basic facial expressions', observation: 'Show the child pictures of happy, sad, angry, surprised faces. Which expressions are recognized most accurately? Which are confused?' },
      { text: 'Engages in simple pretend play', observation: 'Describe recent pretend play scenarios (feeding a doll, driving a car). Does the child assign roles to others? How long do scenes last?' },
      { text: 'Seeks adult comfort when distressed', observation: 'What does the child do when hurt, scared, or frustrated? Do they seek a specific adult? How do they signal need for comfort?' },
      { text: 'Tolerates brief separation from caregiver', observation: 'Describe drop-off behavior. How long until the child settles? What strategies help (transitional object, routine, distraction)?' },
      { text: 'Follows simple group routines (circle time)', observation: 'Describe participation in group activities. Does the child sit, imitate actions, sing? How long do they remain engaged?' },
      { text: 'Shows awareness of being observed by others', observation: 'Does the child modify behavior when watched (perform, show off, hide)? Give a recent example of audience awareness.' },
    ],
    '5-6': [
      { text: 'Engages in cooperative play with shared goals', observation: 'Describe a recent cooperative play scenario (building a block tower together, team game). What role did the child take? How were conflicts resolved?' },
      { text: 'Shares toys or materials without adult prompting', observation: 'Describe sharing behavior. Does the child offer, wait their turn, or resist? How do they react when someone asks to share?' },
      { text: 'Greets peers and adults appropriately', observation: 'Describe typical greeting behavior. Does the child initiate or respond? Do they use eye contact, smile, or verbal greeting?' },
      { text: 'Takes turns in games and conversations', observation: 'Describe turn-taking in a recent game or conversation. Does the child wait patiently, interrupt, or lose interest while waiting?' },
      { text: 'Identifies emotions in others from facial cues', observation: 'Which emotions are identified most/least accurately? Does the child use context (situation) or rely only on facial expression?' },
      { text: 'Creates and sustains imaginative play scenarios', observation: 'Describe a recent imaginative play session. What roles were assigned? How long did the scenario last? Did peers join or reject the play?' },
      { text: 'Seeks peer comfort or companionship when upset', observation: 'When distressed, does the child prefer adult or peer comfort? Describe a recent instance of seeking a specific friend.' },
      { text: 'Functions independently in school or classroom routines', observation: 'Describe morning routine independence. Does the child hang up coat, find seat, and start activity without adult direction?' },
      { text: 'Adapts behavior to different settings (library vs. playground)', observation: 'Give examples of setting-appropriate behavior. Does the child run indoors or whisper on the playground? How quickly do they adjust?' },
      { text: 'Demonstrates awareness of audience when speaking or performing', observation: 'Describe the child\'s behavior during show-and-tell or performance. Do they speak loudly enough, make eye contact, or show stage fright?' },
    ],
    '7-8': [
      { text: 'Participates in group games with rules', observation: 'Describe participation in a recent structured game. Does the child understand and follow rules? How do they react to losing or rule-breaking by others?' },
      { text: 'Compromises during peer disagreements', observation: 'Describe a recent conflict. Did the child offer a compromise, insist on their way, or withdraw? What negotiation strategies were used?' },
      { text: 'Initiates social interactions in unstructured settings', observation: 'During free play or recess, how does the child approach peers? What opening lines or actions do they use? What is the success rate?' },
      { text: 'Respects personal space and boundaries of others', observation: 'Describe the child\'s physical proximity to peers. Do they stand too close, touch without permission, or maintain appropriate distance?' },
      { text: 'Shows empathy when a peer is upset', observation: 'Describe a recent instance of peer distress. How did the child react (ignore, stare, offer comfort, get adult)? What did they say or do?' },
      { text: 'Engages in structured role-play or drama activities', observation: 'Describe participation in skits, role-play, or pretend scenarios. Does the child stay in character? How do they handle scripted vs. improvised dialogue?' },
      { text: 'Seeks help from appropriate sources (peer or adult)', observation: 'When faced with a problem, who does the child ask for help? Do they distinguish between peer-appropriate and adult-appropriate requests?' },
      { text: 'Works independently in small groups without adult hovering', observation: 'Describe a recent group project. Did the child contribute ideas, delegate tasks, or dominate? How was leadership distributed?' },
      { text: 'Adapts behavior based on social feedback from peers', observation: 'Give an example where peers laughed, frowned, or walked away. Did the child modify their behavior afterward? How quickly?' },
      { text: 'Modifies own behavior when receiving positive or negative social feedback', observation: 'Describe how praise or criticism affects the child\'s behavior. Do they repeat praised actions? Do they persist after negative feedback or change approach?' },
    ],
    '9-10': [
      { text: 'Leads or organizes group activities appropriately', observation: 'Describe a recent instance of the child leading. Did they assign roles, set rules, or dictate? How did peers respond to their leadership?' },
      { text: 'Resolves peer conflicts with minimal adult support', observation: 'Describe a recent conflict the child resolved independently. What strategies were used (negotiation, apology, compromise, humor)?' },
      { text: 'Initiates and maintains friendships outside structured settings', observation: 'Does the child have friends outside of school/therapy? How do they maintain contact (calls, playdates, online)? What activities do they share?' },
      { text: 'Understands unwritten social rules in different contexts', observation: 'Give examples of context-specific rules the child understands (e.g., whispering in library, cheering at sports). Which rules are still missed?' },
      { text: 'Offers emotional support to peers in distress', observation: 'Describe a recent instance. What did the child say or do? Was the support appropriate to the situation or awkward/mismatched?' },
      { text: 'Collaborates creatively in group projects', observation: 'Describe a recent group project. Did the child generate original ideas, build on others\' ideas, or prefer to execute instructions? How were creative differences handled?' },
      { text: 'Judges when to seek help vs. handle independently', observation: 'Describe a recent problem. How did the child decide whether to ask for help? What factors influence their decision (difficulty, time pressure, pride)?' },
      { text: 'Works productively in fully independent group settings', observation: 'In a group without adult supervision, does the child stay on task, manage time, and resolve conflicts? Describe a recent example.' },
      { text: 'Modifies own behavior based on peer group norms', observation: 'Describe how peer influence affects the child. Do they adopt slang, clothing preferences, or interests to fit in? Is this flexible or rigid?' },
      { text: 'Manages public speaking or performance anxiety appropriately', observation: 'Describe the child\'s behavior before and during presentations. Do they use coping strategies? What level of anxiety is displayed?' },
    ],
    '11-12+': [
      { text: 'Maintains long-term friendships with reciprocal trust', observation: 'Describe the child\'s longest friendship. What maintains the bond? Is there mutual sharing of secrets, support, and activities? How is conflict handled?' },
      { text: 'Mediates conflicts between peers', observation: 'Describe a time the child stepped in between arguing peers. What did they say or do? Were they successful? How was neutrality maintained?' },
      { text: 'Initiates romantic or deeper social bonds appropriately', observation: 'If applicable, describe how the child expresses interest in deeper relationships. Is the approach respectful and reciprocated? How do they handle rejection?' },
      { text: 'Codeswitches behavior across social contexts (home vs. school)', observation: 'Give examples of different behavior at home versus school. Does the child use different language, manners, or emotional expression? Is this conscious?' },
      { text: 'Provides complex emotional support and perspective-taking', observation: 'Describe a time the child comforted someone experiencing a complex emotion (grief, betrayal). Did they acknowledge the feeling without trying to fix it immediately?' },
      { text: 'Contributes meaningfully to team dynamics and roles', observation: 'In team sports or group projects, what role does the child naturally take (organizer, cheerleader, specialist, peacemaker)? How do they handle role conflicts?' },
      { text: 'Serves as a support figure for younger or struggling peers', observation: 'Describe instances of the child helping younger children or peers with disabilities. Is the help patronizing or empowering? How do they know when to step back?' },
      { text: 'Manages group leadership roles with accountability', observation: 'When in charge, does the child follow through on responsibilities, delegate fairly, and accept blame for group failures? Give examples.' },
      { text: 'Challenges peer group norms constructively when needed', observation: 'Describe a time the child disagreed with the group. How did they express dissent? Were they able to maintain peer relationships while standing their ground?' },
      { text: 'Presents or performs in front of groups with confidence and preparation', observation: 'Describe a recent presentation or performance. Was the child prepared? Did they engage the audience? How did they handle mistakes or unexpected questions?' },
    ],
  },
  Cognitive: {
    '3-4': [
      { text: 'Matches identical objects or pictures', observation: 'Describe matching tasks attempted. Which categories are easiest (colors, shapes, animals)? Does the child match by color instead of shape when instructed otherwise?' },
      { text: 'Completes simple 3–4 piece puzzles', observation: 'Describe puzzle completion behavior. Does the child use trial-and-error or look at the picture? How much adult guidance is needed?' },
      { text: 'Recalls familiar routines in order', observation: 'Ask the child to describe their morning routine. How many steps are recalled? Are they in correct sequence? Are any steps invented or omitted?' },
      { text: 'Sustains attention to preferred activity for 5 minutes', observation: 'Which activities hold attention longest? Describe signs of drifting attention (looking away, fidgeting, switching toys). How is attention re-engaged?' },
      { text: 'Recognizes own name in print', observation: 'Can the child find their name among other names? Do they recognize it in different fonts or only in a specific context (cubby label, paper)?' },
      { text: 'Counts to 10 with 1-to-1 correspondence', observation: 'Observe the child counting objects. Do they point to each item once? Do they skip items or count the same item twice? Can they count backward?' },
      { text: 'Understands concepts of more, less, big, and small', observation: 'Test with two piles of blocks. Can the child identify which has more? Do they use comparison words spontaneously or only when prompted?' },
      { text: 'Copies simple shapes', observation: 'Ask the child to copy a circle, cross, and square. Which shapes are most accurate? Do they draw lines fluidly or in segments?' },
      { text: 'Makes simple choices between 2 options', observation: 'When offered a choice, how does the child decide? Do they hesitate, impulsively grab, or ask for more information? How do they handle having the preferred option taken?' },
      { text: 'Shows curiosity by exploring new toys or materials', observation: 'Describe how the child approaches a new toy. Do they examine it visually, manipulate it, or ask about it? How long does exploration last before moving on?' },
    ],
    '5-6': [
      { text: 'Sorts objects by color, shape, or size', observation: 'Describe a recent sorting task. Can the child sort by one attribute and then re-sort by another? Do they get stuck on their preferred sorting rule?' },
      { text: 'Completes 10–20 piece puzzles independently', observation: 'What puzzle strategies are used (edges first, picture matching, trial-and-error)? How long does completion take? What happens with frustration?' },
      { text: 'Recalls sequence of daily events accurately', observation: 'Ask "What did you do after lunch?" Record the sequence. Are temporal markers used (then, next, after)? Are events accurate or confabulated?' },
      { text: 'Sustains attention to non-preferred tasks for 10 minutes', observation: 'What non-preferred tasks are tolerated? Describe attention-wandering behaviors. What reinforcers or strategies extend attention span?' },
      { text: 'Recognizes common sight words', observation: 'How many sight words are recognized (e.g., the, and, is, to)? Are words recognized in isolation, in sentences, or both? Which words are confused?' },
      { text: 'Performs single-digit addition and subtraction', observation: 'Present 3+2 and 5-2. Does the child count on fingers, use mental math, or need manipulatives? Are subtraction problems harder than addition?' },
      { text: 'Understands time concepts (before, after, yesterday)', observation: 'Ask "What did you do yesterday?" or "What happens before bedtime?" Are temporal concepts understood literally or confused? How is time referenced?' },
      { text: 'Copies letters and numbers legibly', observation: 'Have the child copy their name and numbers 1-10. Are letters/numbers formed correctly, oriented properly, and spaced adequately? Which are hardest?' },
      { text: 'Plans steps to complete a craft or simple project', observation: 'Give a multi-step craft. Does the child gather materials first? Do they sequence steps logically, or do they skip ahead and backtrack?' },
      { text: 'Asks questions to understand how things work', observation: 'What types of questions does the child ask about cause and effect ("Why is the sky blue?", "How does this work?")? Do they persist with follow-up questions?' },
    ],
    '7-8': [
      { text: 'Sorts using multiple attributes simultaneously', observation: 'Present objects that vary in color, shape, and size. Can the child sort by "red circles" vs. "blue squares"? How do they handle conflicting attributes?' },
      { text: 'Completes complex puzzles or logic problems', observation: 'Describe strategies for complex puzzles (100+ pieces, logic grids). Does the child use systematic approaches or guess? How is frustration managed?' },
      { text: 'Recalls and retells stories in correct sequence', observation: 'After hearing a story, ask the child to retell it. Record main events, sequence accuracy, and inclusion of details. Are inferences made or only literal facts?' },
      { text: 'Sustains attention to teacher instruction for 15 minutes', observation: 'During a 15-minute lesson, how many times does attention drift? What triggers distraction (noise, internal thoughts, visual stimuli)? How is focus regained?' },
      { text: 'Reads grade-level text with comprehension', observation: 'Have the child read a grade-level passage. Test literal and inferential comprehension. Can they identify the main idea? What types of questions are missed?' },
      { text: 'Performs multi-digit addition and subtraction with regrouping', observation: 'Present problems requiring carrying and borrowing. Are place values aligned? Are regrouping errors common? Does the child check their work?' },
      { text: 'Tells time on an analog clock and understands calendar', observation: 'Ask the child to show 3:45 on a clock. Can they read half-past, quarter-to? Do they understand days of the week, months, and seasons in order?' },
      { text: 'Writes sentences with proper spacing and punctuation', observation: 'Review a recent writing sample. Are capitals and periods used consistently? Is spacing between words adequate? Are sentences complete or fragments?' },
      { text: 'Organizes materials for multi-step assignments', observation: 'Before starting homework or a project, does the child gather materials, read instructions, and plan steps? Or do they dive in and improvise?' },
      { text: 'Forms hypotheses and tests them through exploration', observation: 'Describe a recent instance of the child making a prediction and testing it ("I think this will sink"). How do they record or remember results?' },
    ],
    '9-10': [
      { text: 'Classifies items using hierarchical categories', observation: 'Ask "Is a poodle a dog, an animal, or a mammal?" Can the child place items in nested categories? Do they understand that all dogs are animals but not vice versa?' },
      { text: 'Solves multi-step logic puzzles or brain teasers', observation: 'Present a Sudoku or logic grid. What strategies are used (elimination, working backward)? How long does the child persist before giving up?' },
      { text: 'Recalls and summarizes academic content after delay', observation: 'Ask about a lesson from last week. What details are retained? Is the summary accurate or filled with confabulation? Are connections made to prior knowledge?' },
      { text: 'Sustains attention through 30+ minute lessons', observation: 'Describe sustained attention during a long lesson. What self-regulation strategies are used (note-taking, fidget tools, self-talk)? When does fatigue set in?' },
      { text: 'Reads and comprehends expository or informational texts', observation: 'Have the child read an informational article. Can they identify text features (headings, captions)? Do they distinguish fact from opinion?' },
      { text: 'Solves grade-level word problems independently', observation: 'Present multi-step word problems. Does the child identify relevant information, choose correct operations, and verify reasonableness of answers?' },
      { text: 'Manages time and deadlines for assignments independently', observation: 'Does the child use a planner or calendar? Describe a recent assignment deadline. Was it met? How was time allocated across days?' },
      { text: 'Writes structured paragraphs with topic sentences', observation: 'Review a recent paragraph. Is there a clear topic sentence, supporting details, and concluding sentence? Are transitions used between ideas?' },
      { text: 'Uses organizational strategies (planner, checklist) independently', observation: 'What organizational tools does the child use without prompting? Describe how they prioritize tasks. Are checklists created mentally or on paper?' },
      { text: 'Designs simple experiments or research inquiries', observation: 'Describe a recent science or research project. Did the child identify variables, predict outcomes, and draw conclusions? How was data collected?' },
    ],
    '11-12+': [
      { text: 'Creates original classification systems', observation: 'Ask the child to organize a set of items their own way. Is the system logical, hierarchical, or creative? Can they justify their categories?' },
      { text: 'Engages in strategic games requiring planning (chess, etc.)', observation: 'Describe gameplay. Does the child think multiple moves ahead, anticipate opponent moves, and adapt strategy? How do they handle losing?' },
      { text: 'Retains and applies learned information across subjects', observation: 'Give an example of the child applying math skills in science, or reading strategies in history. Do they recognize cross-curricular connections independently?' },
      { text: 'Sustains focus through multi-period projects and exams', observation: 'Describe preparation for a major exam or project. How is study time distributed? What breaks or strategies prevent burnout? How is test anxiety managed?' },
      { text: 'Reads, critiques, and compares complex texts', observation: 'Present two articles on the same topic with different perspectives. Can the child identify bias, compare evidence quality, and form an independent conclusion?' },
      { text: 'Applies math to real-world scenarios (budgeting, measurement)', observation: 'Describe a real-world math application attempted (shopping budget, cooking measurements). Can the child translate a word problem into an equation and back?' },
      { text: 'Plans long-term projects with milestone scheduling', observation: 'Review a recent long-term project plan. Were milestones defined with dates? Was progress monitored? How were delays handled?' },
      { text: 'Writes multi-paragraph essays with thesis and evidence', observation: 'Review a recent essay. Is there a clear thesis, body paragraphs with topic sentences, textual evidence, and a conclusion? Is citation attempted?' },
      { text: 'Self-monitors progress and revises plans independently', observation: 'Describe a time the child noticed they were behind schedule and adjusted. What self-monitoring cues are used (checklists, time checks, gut feeling)?' },
      { text: 'Conducts independent research and evaluates sources', observation: 'Describe a recent research task. How were sources found and selected? Can the child distinguish credible from non-credible sources? Is plagiarism avoided?' },
    ],
  },
  Motor: {
    '3-4': [
      { text: 'Runs without falling frequently', observation: 'Observe the child running across the room or playground. Do their arms swing opposite to legs? Do they trip over flat surfaces or obstacles?' },
      { text: 'Jumps with two feet', observation: 'Ask the child to jump over a line or off a low step. Do both feet leave and land together? Is there a preparatory bend of knees?' },
      { text: 'Climbs playground equipment confidently', observation: 'Describe climbing on stairs, ladders, or slides. Does the child alternate feet? Do they use a handrail? What height is comfortable vs. scary?' },
      { text: 'Throws a ball in general direction', observation: 'Have the child throw a ball to you. Which hand is used? Does the ball go forward or sideways? Is there a step-forward motion?' },
      { text: 'Stacks 6+ blocks steadily', observation: 'Provide blocks and ask for a tall tower. How many blocks are stacked before it falls? Is the tower centered or does it lean? How is frustration handled?' },
      { text: 'Uses spoon or fork without spilling most of meal', observation: 'Observe a meal or snack. Does the child hold utensil correctly (not fist grip)? How much food is spilled? Do they switch hands?' },
      { text: 'Draws recognizable simple figure (stick person)', observation: 'Ask the child to draw a person. How many body parts are included? Is the drawing recognizable? Which parts are omitted or disproportional?' },
      { text: 'Manipulates small buttons, beads, or pegs', observation: 'Provide a button board or bead stringing task. Does the child use a pincer grasp? How is bilateral coordination (holding with one hand, manipulating with the other)?' },
      { text: 'Shows appropriate muscle tone (not floppy or rigid)', observation: 'Describe muscle tone during movement and rest. Is there low tone (slumping, loose joints) or high tone (stiffness, limited range)? How does tone affect function?' },
      { text: 'Reacts appropriately to tactile input (avoids or over-seeks)', observation: 'Describe reaction to textures (sand, paint, sticky glue). Does the child avoid messy play, crave it, or tolerate it briefly? How is self-regulation attempted?' },
    ],
    '5-6': [
      { text: 'Runs with coordinated arm and leg movement', observation: 'Observe running form. Are arms bent at 90 degrees and swinging opposite to legs? Is there a clear flight phase? How is endurance over distance?' },
      { text: 'Hops on one foot 5+ times', observation: 'Ask the child to hop on each foot. Which foot is dominant? Is balance maintained without putting the other foot down? Are arms used for balance?' },
      { text: 'Climbs ladders and monkey bars with alternating hands', observation: 'Describe climbing with alternating hand-over-hand motion. Is there fear of heights? How is grip strength? Can they traverse monkey bars independently?' },
      { text: 'Throws with aim toward a target (underhand or overhand)', observation: 'Have the child throw a beanbag at a target. Which throw style is used? Is there trunk rotation and step-forward? How accurate is the aim?' },
      { text: 'Copies basic shapes (circle, square, cross)', observation: 'Ask the child to copy shapes. Are corners sharp on the square? Is the circle closed? Does the child stabilize the paper with one hand while drawing?' },
      { text: 'Uses knife to spread and cuts soft food', observation: 'Observe spreading butter or cutting a banana. Is the knife held correctly? Is there reciprocal sawing motion? How is safety awareness?' },
      { text: 'Draws person with 6+ body parts', observation: 'Ask for a drawing of a person. Count body parts (head, body, arms, legs, hands, feet, facial features). Are parts proportionate and connected correctly?' },
      { text: 'Uses dominant hand consistently for fine tasks', observation: 'Observe handedness across tasks (drawing, eating, throwing). Is dominance consistent? If mixed, which hand is preferred for precision tasks?' },
      { text: 'Maintains seated posture at desk or table for activities', observation: 'Describe sitting posture during table tasks. Is the child upright, slumped, or wiggling? Do feet touch the floor? Is there a need for adaptive seating?' },
      { text: 'Tolerates varied textures in hands, mouth, or clothing', observation: 'Describe tolerance for different fabrics, food textures, or art materials. Which textures are accepted vs. refused? Is there oral seeking or avoidance?' },
    ],
    '7-8': [
      { text: 'Runs with speed and participates in structured running games', observation: 'Describe participation in tag or relay races. Is the child competitive? How is sportsmanship? Do they understand game strategy or just chase?' },
      { text: 'Skips with alternating feet', observation: 'Ask the child to skip across the room. Is the rhythm smooth (step-hop, step-hop)? Do arms swing in opposition? How does it compare to peers?' },
      { text: 'Climbs with planning and body awareness', observation: 'Describe climbing on a complex structure. Does the child plan hand/foot placement ahead? Are they aware of body in space (not bumping into things)?' },
      { text: 'Catches a ball with hands only (no trapping against body)', observation: 'Throw a medium-sized ball to the child. Do they extend arms and trap with hands? Do they close arms against chest? Which ball sizes are easiest?' },
      { text: 'Copies complex shapes and letters with proper formation', observation: 'Have the child copy triangles, diamonds, and lowercase letters. Are diagonal lines accurate? Is letter formation top-to-bottom and left-to-right?' },
      { text: 'Ties shoelaces independently', observation: 'Ask the child to tie their shoes. Which method is used (bunny ears, loop-swoop)? How long does it take? Is the knot secure and balanced?' },
      { text: 'Draws detailed scenes with background and foreground', observation: 'Ask for a drawing of a house and yard. Are there background elements (sun, grass, sky)? Is there depth (things in front vs. behind)? How detailed are figures?' },
      { text: 'Uses tools (glue, tape, stapler) in construction tasks', observation: 'Describe a recent craft project. Can the child operate scissors, apply glue neatly, and use a ruler? Is tool use efficient or awkward?' },
      { text: 'Sits with appropriate posture during 20+ minute tasks', observation: 'During a 20-minute task, describe posture changes. Does the child sit on their feet, wrap legs around chair, or fall out of seat? Is a wobble cushion or band used?' },
      { text: 'Tolerates messy play and varied sensory activities', observation: 'Describe participation in finger painting, clay, or water play. Does the child wear the activity or actively explore? How is cleanup handled?' },
    ],
    '9-10': [
      { text: 'Participates in competitive or endurance running', observation: 'Describe performance in running activities. Is there pacing strategy or sprint-and-stop pattern? How is breathing controlled? What distance is comfortable?' },
      { text: 'Performs skipping, galloping, and sliding smoothly', observation: 'Observe locomotor skills in gym class. Are transitions between movements smooth? Is there rhythm and flow, or stiffness and hesitation?' },
      { text: 'Navigates complex climbing or challenge courses', observation: 'Describe performance on obstacle courses. Is there planning, balance, and coordination? How is fear managed? Are safety rules followed?' },
      { text: 'Catches with one hand or while moving', observation: 'Throw a ball to the side while the child is moving. Can they adjust body position to catch? Is hand-eye coordination consistent across directions?' },
      { text: 'Writes with consistent size, slant, and spacing', observation: 'Review a paragraph of handwriting. Is sizing uniform? Is slant consistent? Are letters and words adequately spaced? Is legibility maintained at speed?' },
      { text: 'Ties knots, uses scissors, ruler with precision', observation: 'Describe precision tasks attempted. Can the child tie a double knot, cut along a line, or measure accurately? Which tasks are still effortful?' },
      { text: 'Creates detailed artwork with shading or perspective', observation: 'Review recent artwork. Is there use of light/dark, overlapping, or relative size to show depth? How does the child respond to artistic feedback?' },
      { text: 'Assembles models or kits following complex instructions', observation: 'Describe a model or LEGO set built from instructions. Were steps followed sequentially? Were mistakes caught and corrected? How was persistence?' },
      { text: 'Maintains ergonomic posture during extended desk work', observation: 'During 30+ minutes of desk work, describe posture. Are shoulders hunched, head down, or back curved? Does the child self-correct when reminded?' },
      { text: 'Manages sensory needs independently in busy environments', observation: 'In a loud or crowded setting, what does the child do to self-regulate? Do they use noise-canceling headphones, seek quiet corners, or have a fidget tool?' },
    ],
    '11-12+': [
      { text: 'Engages in organized sports with refined technique', observation: 'Describe skill level in a chosen sport. Is there refined technique (proper form, strategy)? How is coaching feedback received and applied?' },
      { text: 'Performs complex motor sequences (dance, martial arts)', observation: 'Describe performance in a choreographed sequence. Is memory for long sequences accurate? Is timing and coordination with music or partners consistent?' },
      { text: 'Engages in adventure or ropes-course activities independently', observation: 'Describe participation in high-challenge activities. Is there fear management, safety awareness, and peer encouragement? How is risk assessed?' },
      { text: 'Plays ball sports requiring rapid reaction and precision', observation: 'Describe performance in sports like tennis, volleyball, or basketball. Is there anticipation of ball trajectory? Are split-second decisions accurate?' },
      { text: 'Produces cursive or typed work efficiently and legibly', observation: 'Compare handwriting vs. typing output. Which is faster and more legible? Is touch-typing used? Are digital tools (spell-check, grammar) utilized effectively?' },
      { text: 'Uses complex tools (compass, sewing, instruments) accurately', observation: 'Describe skill with specialized tools. Is there precision and safety awareness? Can the child troubleshoot when a tool does not work as expected?' },
      { text: 'Creates original artwork or crafts with refined technique', observation: 'Review a recent creative project. Is there evidence of planning, skill refinement, and personal style? How is constructive criticism received?' },
      { text: 'Builds or repairs mechanical or technical items independently', observation: 'Describe a recent build or repair project. Did the child read instructions, identify needed parts, and execute steps? Were errors diagnosed and fixed?' },
      { text: 'Self-corrects posture and seeks ergonomic adaptations', observation: 'Does the child independently adjust their chair height, monitor position, or take stretch breaks? Are they aware of body signals (stiffness, fatigue)?' },
      { text: 'Advocates for and implements personal sensory regulation strategies', observation: 'Describe how the child manages sensory needs proactively. Do they request accommodations, carry sensory tools, or excuse themselves to regroup?' },
    ],
  },
  Autonomy: {
    '3-4': [
      { text: 'Indicates toileting needs verbally or with gesture', observation: 'Describe signals used for toileting (words, hand signs, heading to bathroom). How often are signals accurate vs. late? What is the success rate of making it to the toilet?' },
      { text: 'Feeds self finger foods and drinks from cup', observation: 'Observe a meal. Does the child pick up food with pincer grasp? Is the cup held with two hands or one? How much spilling occurs?' },
      { text: 'Cooperates with dressing (puts arms in sleeves)', observation: 'Describe dressing participation. Can the child find armholes, push arms through, or pull up pants? Which clothing items are easiest/hardest?' },
      { text: 'Sleep routine is predictable with adult guidance', observation: 'Describe the bedtime routine. How long does it take? What steps are involved (bath, story, song)? Is falling asleep quick or prolonged?' },
      { text: 'Acknowledges dangerous situations (hot, sharp)', observation: 'Describe reactions to hazards. Does the child avoid a hot stove or sharp scissors? How is danger learned (experience, instruction, observation)?' },
      { text: 'Puts away toys when prompted', observation: 'When asked to clean up, does the child sort items to correct places or dump randomly? How much prompting is needed (verbal, visual, hand-over-hand)?' },
      { text: 'Brushes teeth with adult supervision', observation: 'Observe toothbrushing. Does the child apply toothpaste, brush all surfaces, and spit? How much physical guidance is still needed?' },
      { text: 'Acknowledges hunger and fullness cues', observation: 'Does the child ask for food when hungry or leave food when full? Are cues recognized accurately, or is eating driven by emotion or availability?' },
      { text: 'Accepts help when frustrated', observation: 'When a task is too hard, does the child ask for help, give up, or tantrum? How is help accepted (gracefully, resentfully, eagerly)?' },
      { text: 'Shows preference for activities or toys', observation: 'Describe how the child expresses preferences. Do they reach, point, name, or physically obtain desired items? Are preferences stable or changeable?' },
    ],
    '5-6': [
      { text: 'Uses toilet independently and washes hands afterward', observation: 'Describe bathroom independence. Does the child handle all steps (wipe, flush, wash, dry)? Is thoroughness adequate or do they rush?' },
      { text: 'Uses utensils properly for full meal', observation: 'Observe knife and fork use. Is cutting motion reciprocal? Is food loaded onto fork correctly? Is the non-dominant hand used to stabilize the plate?' },
      { text: 'Dresses self independently including buttons and zippers', observation: 'Which fasteners are mastered (buttons, zippers, snaps, buckles)? Which still need help? Is clothing put on front-to-back correctly?' },
      { text: 'Follows bedtime routine with minimal reminders', observation: 'Describe the evening routine. How many reminders are needed? Does the child initiate steps (putting on pajamas, brushing teeth) independently?' },
      { text: 'Follows basic safety rules (look both ways, stranger)', observation: 'Describe safety awareness in real situations. Does the child look before crossing? How do they respond to unfamiliar adults approaching?' },
      { text: 'Cleans up work or activity space without reminder', observation: 'When an activity ends, does the child spontaneously tidy? Is cleanup thorough or superficial? Are materials returned to correct locations?' },
      { text: 'Brushes teeth and hair independently', observation: 'Observe grooming. Is toothbrushing duration adequate (2 minutes)? Is hair brushing tangle-free? Are these done without prompting?' },
      { text: 'Recognizes and communicates physical discomfort or illness', observation: 'When not feeling well, how does the child communicate this (words, behavior change, pointing to body part)? Is the description specific or vague?' },
      { text: 'Uses simple calming strategies when upset (deep breaths)', observation: 'When upset, what self-soothing strategies are used? Are they effective? Does the child need adult prompting to use strategies?' },
      { text: 'Makes choices between multiple activities independently', observation: 'When given free time, how does the child choose activities? Is the decision quick or agonizing? Do they stick with the choice or flip between options?' },
    ],
    '7-8': [
      { text: 'Manages full bathroom routine independently', observation: 'Describe complete bathroom independence including flushing, handwashing with soap, and drying. Is privacy requested? Are hygiene standards adequate?' },
      { text: 'Prepares simple snacks independently', observation: 'Can the child pour cereal, spread peanut butter, or make a sandwich? Is safety observed (knife use, not eating raw ingredients)? How is cleanup?' },
      { text: 'Selects weather-appropriate clothing independently', observation: 'On a rainy day, does the child choose a coat and boots without prompting? Are layers understood? Is there resistance to practical choices?' },
      { text: 'Independently initiates bedtime routine at appropriate time', observation: 'Does the child recognize when it is bedtime and begin routine steps? Is a clock or parent reminder still needed? How is wind-down managed?' },
      { text: 'Navigates neighborhood or school safely without direct supervision', observation: 'Describe independent navigation. Does the child look for cars, stay on sidewalks, and arrive at destination? Are boundaries respected?' },
      { text: 'Keeps personal workspace organized independently', observation: 'Describe desk or cubby organization. Are materials in designated places? Is there a system, or is it organized chaos? How often is tidying needed?' },
      { text: 'Performs full grooming routine independently', observation: 'Which grooming tasks are done without prompting (hair, teeth, washing face, nails)? Is quality parent-approved or does adult checking reveal missed spots?' },
      { text: 'Self-monitors health and asks for help when sick or injured', observation: 'When injured, does the child assess severity accurately? Do they overreact to minor scrapes or underreact to significant pain? How do they request help?' },
      { text: 'Uses taught self-regulation strategies independently', observation: 'Which coping strategies are used without prompting (deep breathing, counting, quiet corner)? Are they used before escalation or only after meltdown begins?' },
      { text: 'Prioritizes preferred vs. non-preferred tasks', observation: 'When given a to-do list, does the child tackle hard tasks first or procrastinate? How is motivation maintained for non-preferred activities?' },
    ],
    '9-10': [
      { text: 'Maintains hygiene independently throughout the school day', observation: 'Does the child use hand sanitizer, wash hands after restroom, and manage personal cleanliness without adult reminders? Are there social awareness cues (body odor, messy face)?' },
      { text: 'Prepares simple meals (sandwich, cereal) independently', observation: 'Can the child safely use toaster, microwave, or stove with supervision? Is nutrition considered, or are sugary snacks preferred? How is kitchen safety?' },
      { text: 'Selects socially appropriate outfits for occasions', observation: 'Does the child distinguish between school clothes, sports clothes, and dressy clothes? Are choices influenced by peer trends or weather appropriateness?' },
      { text: 'Manages sleep schedule to meet daily demands', observation: 'Does the child self-regulate bedtime to wake up rested? Are electronic devices managed independently? How is weekend vs. weekday sleep handled?' },
      { text: 'Makes safe judgments in unfamiliar environments', observation: 'In a new place (mall, park, friend\'s house), does the child stay with the group, assess exits, and avoid strangers? How is independence balanced with caution?' },
      { text: 'Maintains organization of materials across multiple subjects', observation: 'Describe binder, backpack, and locker organization. Are subjects separated? Is there a homework folder? How often are items lost?' },
      { text: 'Manages grooming with awareness of social standards', observation: 'Is the child aware of peer grooming standards? Do they care about appearance, or is hygiene resisted? How are feedback and teasing handled?' },
      { text: 'Manages minor first aid and medication reminders', observation: 'Can the child apply a bandage, use ice, or remind an adult about medication? Do they know when a situation exceeds their capability and requires adult help?' },
      { text: 'Applies self-regulation in high-stress academic or social situations', observation: 'Describe coping during a test, presentation, or peer conflict. Which strategies are used? Are they effective, or does stress impair performance?' },
      { text: 'Negotiates to balance wants vs. obligations', observation: 'When asked to do chores before play, does the child negotiate ("Can I finish this level first?")? Are negotiations reasonable and respectful?' },
    ],
    '11-12+': [
      { text: 'Manages complex hygiene routines independently (skincare, etc.)', observation: 'Which advanced hygiene tasks are performed (shaving, skincare, deodorant)? Is there embarrassment or openness about bodily changes? How is privacy managed?' },
      { text: 'Plans and prepares balanced meals independently', observation: 'Can the child plan a menu, shop for ingredients, and cook a full meal? Are nutritional balance and food safety considered? How is budgeting handled?' },
      { text: 'Manages laundry, clothing care, and wardrobe planning', observation: 'Does the child sort laundry, operate machines, and iron? Is clothing cared for (hung up, not crumpled)? How far ahead is clothing planned?' },
      { text: 'Self-regulates sleep and energy for academic or athletic demands', observation: 'During exam periods or sports seasons, does the child adjust sleep and nutrition proactively? Are energy drinks or naps used strategically?' },
      { text: 'Assesses risk and makes independent safety decisions', observation: 'Describe a recent safety decision made independently. Was risk accurately assessed? What information was considered (peer pressure, consequences, past experience)?' },
      { text: 'Manages systems for organization (digital and physical)', observation: 'What organizational tools are used (apps, planners, color-coding)? Are digital files organized? Is there a backup system for important documents?' },
      { text: 'Maintains consistent grooming aligned with identity and context', observation: 'Does grooming reflect personal identity (style, cultural norms, gender expression)? Is there flexibility across contexts (conservative for school, expressive for social)?' },
      { text: 'Independently manages health appointments and medication', observation: 'Does the child schedule appointments, prepare questions, and manage prescription refills? Is medication taken on time without external reminders?' },
      { text: 'Develops personalized coping systems proactively', observation: 'Describe the child\'s unique coping toolkit. Have they invented strategies, or do they only use taught ones? How is the toolkit adjusted for different stressors?' },
      { text: 'Sets long-term personal goals and follows through', observation: 'What long-term goals has the child set (academic, athletic, creative)? Are goals specific and realistic? Describe progress and obstacles encountered.' },
    ],
  },
  Behavior: {
    '3-4': [
      { text: 'Responds to "no" or "stop" with adult guidance', observation: 'When told "no," does the child pause, protest, or comply? How long does compliance last? What type of guidance is most effective (explanation, distraction, consequence)?' },
      { text: 'Transitions between activities with adult support', observation: 'Describe a recent transition. How much warning is needed? What strategies help (timer, countdown, visual schedule)? What is the intensity of resistance?' },
      { text: 'Calms within 10 minutes with adult soothing', observation: 'When upset, what soothing strategies work (hugs, quiet voice, favorite toy)? How long does calming take? What re-triggers distress during the calming process?' },
      { text: 'Shows no self-injurious behaviors (SIB)', observation: 'Describe any SIB observed (head-banging, biting, scratching). What triggers it? How severe is it? What interventions have been tried?' },
      { text: 'Shows no aggression toward others', observation: 'Describe any aggressive behavior (hitting, kicking, throwing). What precedes it? Is it impulsive or intentional? How is it redirected?' },
      { text: 'Tolerates minor changes in routine', observation: 'Describe a recent routine change. What was the reaction? How long until acceptance? What level of advance notice is needed?' },
      { text: 'Engages in repetitive motor behaviors occasionally', observation: 'Describe repetitive behaviors (hand-flapping, rocking, spinning). When do they occur (excitement, stress, boredom)? How often per hour? Are they disruptive?' },
      { text: 'Responds positively to praise and rewards', observation: 'What types of praise are most effective (specific, enthusiastic, private)? What rewards motivate (stickers, tokens, activities)? Is motivation intrinsic or extrinsic?' },
      { text: 'Remains seated for brief group activity (5 minutes)', observation: 'During circle time or story time, how long does the child sit? What behaviors occur when attention wanes (fidgeting, leaving, calling out)?' },
      { text: 'Seeks attention appropriately (not disruptive)', observation: 'How does the child seek attention (raising hand, calling name, tapping)? Is it proportional to the need? How is inappropriate attention-seeking redirected?' },
    ],
    '5-6': [
      { text: 'Accepts limits and redirection with minimal protest', observation: 'When a preferred activity must end, what is the reaction? Is negotiation attempted? How quickly is redirection accepted? What de-escalation strategies work?' },
      { text: 'Transitions with timer or visual cue', observation: 'Does the child respond to a 2-minute warning or visual timer? Can they self-monitor time remaining? What happens when the timer rings?' },
      { text: 'Calms within 5 minutes using taught strategies', observation: 'Which taught strategies are used (deep breathing, counting, quiet corner)? Does the child initiate strategy use or wait for adult prompt? How effective is each strategy?' },
      { text: 'Rarely displays SIB under stress', observation: 'Under what stressors does SIB emerge? How is it managed? Is there a functional behavior assessment (FBA) or replacement behavior in place?' },
      { text: 'Rarely hits or kicks and uses words instead', observation: 'When angry, does the child use words ("I\'m mad!") or physical aggression? What verbal tools are in their repertoire? How is physical aggression prevented?' },
      { text: 'Tolerates planned changes with preparation', observation: 'When prepared for a change (e.g., field trip, substitute teacher), is tolerance improved? What preparation format works best (social story, verbal explanation, visit)?' },
      { text: 'Repetitive behaviors are brief and not disruptive', observation: 'Describe current repetitive behaviors. How long do episodes last? Can the child stop when asked? Do peers notice or comment?' },
      { text: 'Motivated by token systems or point charts', observation: 'What token economy is in place? Is the child engaged with earning and exchanging tokens? Are preferred reinforcers varied or consistent?' },
      { text: 'Remains seated and attentive for 10–15 minutes', observation: 'During a 15-minute activity, describe attention patterns. Are fidget tools used? How many redirections are needed? Is attention better at the start or end?' },
      { text: 'Uses appropriate strategies to gain adult attention', observation: 'Describe appropriate attention-seeking. Does the child wait for a pause, raise their hand, or use a quiet voice? How are inappropriate attempts corrected?' },
    ],
    '7-8': [
      { text: 'Accepts "no" with verbal protest only (no aggression)', observation: 'When denied a request, what does the child say? Is protest brief or prolonged? Are there verbal escalations ("You\'re mean!", threats)? How is acceptance reached?' },
      { text: 'Transitions independently when given warning', observation: 'With a 5-minute warning, does the child prepare to transition independently? Do they finish their current task, put materials away, and move without protest?' },
      { text: 'Calms within 2–3 minutes with minimal adult intervention', observation: 'Describe a recent upset. How did self-regulation begin? Was adult presence needed, or did the child seek a quiet space independently? What strategy was used?' },
      { text: 'Has functional replacement behavior for SIB urge', observation: 'What replacement behavior is taught (squeezing a stress ball, requesting a break)? Is it used consistently when the urge for SIB arises? How was it shaped?' },
      { text: 'Uses words to express anger or frustration consistently', observation: 'Give examples of anger expressed verbally. Is the vocabulary appropriate ("I\'m frustrated" vs. "I hate you")? How is the intensity of emotion matched to words?' },
      { text: 'Tolerates unplanned changes with brief upset', observation: 'Describe a recent unexpected change (fire drill, canceled activity). How long did distress last? Was recovery spontaneous or scaffolded? What helped most?' },
      { text: 'Uses self-monitoring to reduce repetitive behaviors', observation: 'Does the child notice when repetitive behavior starts and stop themselves? Is a self-monitoring checklist or wristband used? How is progress tracked?' },
      { text: 'Motivated by social praise and internal satisfaction', observation: 'What motivates the child more: adult praise, peer recognition, or personal pride? Give examples of each. Is motivation consistent across settings?' },
      { text: 'Remains seated and on-task for 20+ minutes', observation: 'During independent work, describe on-task behavior. Are breaks self-initiated or scheduled? What is the quality of work produced during sustained attention?' },
      { text: 'Uses appropriate strategies to gain peer attention', observation: 'How does the child approach peers appropriately (inviting to play, complimenting, sharing)? Are there instances of interrupting, boasting, or excluding?' },
    ],
    '9-10': [
      { text: 'Accepts disappointment and negotiates alternatives', observation: 'When plans fall through, does the child negotiate ("Can we do it tomorrow?") or accept graciously? How is the intensity of disappointment managed?' },
      { text: 'Transitions flexibly even with unexpected changes', observation: 'Describe a recent abrupt change. Was the child able to pivot quickly? What self-talk or coping statements were used? How did they support peers who were upset?' },
      { text: 'Recovers from upset independently and returns to task', observation: 'After a frustration, describe the recovery process. Does the child take a walk, use a strategy, or seek a brief break? How long until full re-engagement?' },
      { text: 'No SIB and uses coping toolkit independently', observation: 'What is in the child\'s coping toolkit? Describe a recent instance of independent toolkit use. How was the strategy selected for the specific situation?' },
      { text: 'Resolves anger through problem-solving or cooling off', observation: 'When angry, does the child use a "cool-down" plan or engage in problem-solving? Which approach is preferred? How is the resolution communicated to others?' },
      { text: 'Adapts to unplanned changes flexibly', observation: 'Describe overall flexibility. Is the child generally adaptable, or do specific types of changes (social, schedule, sensory) still trigger distress?' },
      { text: 'Rarely displays repetitive behaviors in public settings', observation: 'Are repetitive behaviors context-dependent? Do they appear at home but not school, or vice versa? How is self-awareness of public vs. private behavior developing?' },
      { text: 'Sets own goals and self-rewards for achievement', observation: 'Describe self-set goals. Are they realistic and measurable? How are rewards chosen? Does the child follow through on self-promises?' },
      { text: 'Sustains on-task behavior for full class periods', observation: 'During a 45-minute class, describe on-task percentage. What internal or external strategies sustain focus? How is off-task behavior self-corrected?' },
      { text: 'Balances attention-seeking with group needs', observation: 'In group settings, does the child dominate or share airtime? Can they step back and let others lead? How is this balance learned and maintained?' },
    ],
    '11-12+': [
      { text: 'Accepts constructive criticism and adjusts behavior', observation: 'When given feedback, does the child become defensive, dismissive, or reflective? Describe a recent example of behavioral change following criticism.' },
      { text: 'Handles abrupt schedule changes without distress', observation: 'Describe a recent last-minute change. Was there any physiological reaction (racing heart, irritability)? How was calm maintained? What preparation helped?' },
      { text: 'Recovers quickly and reflects on trigger afterward', observation: 'After an emotional episode, does the child analyze what triggered it? Is there insight ("I got upset because I was tired")? How is reflection used to prevent recurrence?' },
      { text: 'No SIB and mentors others in coping strategies', observation: 'Does the child teach younger peers or classmates their coping strategies? How is this mentorship received? Does helping others reinforce their own regulation?' },
      { text: 'Channels frustration into constructive action or advocacy', observation: 'Describe a time frustration led to positive action (starting a petition, writing a letter, practicing harder). How is negative energy transformed?' },
      { text: 'Thrives in dynamic environments and seeks novelty', observation: 'Does the child prefer routine or novelty? Describe how they handle dynamic environments (new schools, travel, changing teams). Is flexibility a strength or challenge?' },
      { text: 'Has full awareness and management of own stims or behaviors', observation: 'Can the child name their own repetitive behaviors and explain their function (self-soothing, focus, expression of joy)? How is management balanced with self-acceptance?' },
      { text: 'Driven by internal values and long-term outcomes', observation: 'What values drive the child\'s behavior (fairness, achievement, kindness, independence)? How do these values influence daily choices and long-term planning?' },
      { text: 'Sustains focus across multi-day assignments or projects', observation: 'Describe management of a week-long project. Was time allocated across days? Were distractions managed? How was motivation sustained through boring phases?' },
      { text: 'Gives attention and support to others appropriately', observation: 'Describe how the child supports friends or classmates. Is support given without expectation of return? How are boundaries maintained so the child is not depleted?' },
    ],
  },
};

export function getAgeTierFromAge(ageYears: number): AgeTier {
  if (ageYears <= 4) return '3-4';
  if (ageYears <= 6) return '5-6';
  if (ageYears <= 8) return '7-8';
  if (ageYears <= 10) return '9-10';
  return '11-12+';
}

export function computeDimensionScore(scores: number[]): number {
  if (scores.length === 0) return 0;
  const sum = scores.reduce((a, b) => a + b, 0);
  const max = scores.length * 5;
  const min = scores.length * 1;
  return Math.round(((sum - min) / (max - min)) * 100);
}
